[project]
name = "sort-tr-docs"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "coloredlogs>=15.0.1",
    "jsonpath-ng>=1.7.0",
    "pathvalidate>=3.3.1",
    "pyyaml>=6.0.3",
]

[tool.pytest.ini_options]
pythonpath = "."

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
